In [2]:
import numpyas np

SyntaxError: invalid syntax (1872338585.py, line 1)

In [3]:
import numpy as np

In [4]:
Creating Numpy Array

SyntaxError: invalid syntax (110166245.py, line 1)

In [5]:
list ((2,4,5))

[2, 4, 5]

In [8]:
array=np.array([1,4,7])

In [9]:
type(array)

numpy.ndarray

In [10]:
array.ndim

1

In [11]:
array.shape

(3,)

In [12]:
list1 =[1,2,3]
array =np.array(list1)

In [13]:
print (type(array))
print (array.ndim)
print (array.shape)

<class 'numpy.ndarray'>
1
(3,)


In [16]:
list2=[
    [1,5,9],
    [6,8,2]
]
array2=np.array(list2)

In [17]:
print (array2)
print(array2.ndim)
print (array2.shape)

[[1 5 9]
 [6 8 2]]
2
(2, 3)


In [18]:
print (np.zeros(5))

[0. 0. 0. 0. 0.]


In [20]:
print (np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
print (np.ones((5,5))+1)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [23]:
print (np.identify(4))

AttributeError: module 'numpy' has no attribute 'identify'

In [24]:
print (np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
print (np.random.rand(2,3))

[[0.41090765 0.2548366  0.67805981]
 [0.7590035  0.14571832 0.03282564]]


In [26]:
list(range(5,55,3))

[5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53]

In [27]:
np.arrange(1,10,2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [29]:
np.arange(2.22,90.67,2.45))

SyntaxError: unmatched ')' (3396613378.py, line 1)

In [30]:
np.arange(2.22,90.67,2.45)

array([ 2.22,  4.67,  7.12,  9.57, 12.02, 14.47, 16.92, 19.37, 21.82,
       24.27, 26.72, 29.17, 31.62, 34.07, 36.52, 38.97, 41.42, 43.87,
       46.32, 48.77, 51.22, 53.67, 56.12, 58.57, 61.02, 63.47, 65.92,
       68.37, 70.82, 73.27, 75.72, 78.17, 80.62, 83.07, 85.52, 87.97,
       90.42])

In [32]:
#np.linspace(start,stop, no_element)>linear space 
array_linespace1=np.linspace(start=0,stop=10,num=100)
print (array_linespace1)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [35]:
array_linespace1 = np.linspace(start=(0,0,0), stop =(10,20,30),num=5,axis=0)
print(array_linespace1)

[[ 0.   0.   0. ]
 [ 2.5  5.   7.5]
 [ 5.  10.  15. ]
 [ 7.5 15.  22.5]
 [10.  20.  30. ]]


In [38]:
diag_array= np.diag([3,6,3,6])
diag_array

array([[3, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 6]])

In [39]:
print (np.eye(N=4,M=6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [40]:
np.random.randit ()
                                                                    

AttributeError: module 'numpy.random' has no attribute 'randit'

In [42]:
nDarray=np.random.randint(low=4,high=34,size =(1,2,3,4))
nDarray.shape

(1, 2, 3, 4)

In [47]:
nDarray.shape

(1, 2, 3, 4)

In [48]:
nDarray


array([[[[22, 33, 11,  9],
         [14, 29, 27,  8],
         [29, 15,  8, 13]],

        [[24, 13, 33, 13],
         [28, 17, 14, 11],
         [25,  5,  4, 16]]]], dtype=int32)