slicing 
## hello

In [1]:
## Slicing 

## Slicing 

In [2]:
a= np.array([1,5,3,7])

NameError: name 'np' is not defined

In [3]:
import numpy as np 

In [4]:
a = np.array([1,5,3,7])

In [5]:
print (a[0])

1


In [6]:
print(a[1::2])

[5 7]


In [14]:
#2D ARRAY>SIMILAR TO MATRIX 
list2=([[2,5,7,4],[4,9,11,82],[64,6,34,99],[65,6,34,99]])
array2=np.array(list2)
array2

array([[ 2,  5,  7,  4],
       [ 4,  9, 11, 82],
       [64,  6, 34, 99],
       [65,  6, 34, 99]])

In [15]:
print (array2[1][2])


11


In [16]:
array2.shape

(4, 4)

In [17]:
# print (array2[<row_slice>,<col_slice>])
print (array2[::2,1:3])

[[ 5  7]
 [ 6 34]]


In [18]:
#ND Array
random_array =np.random.randint(low=10,high=50,size=(2,3,4))

In [19]:
print (random_array)

[[[36 47 17 26]
  [32 38 45 47]
  [41 32 32 23]]

 [[45 14 23 24]
  [49 14 16 22]
  [36 41 12 10]]]


In [22]:
# Find element : 1st Matrix ,2*2 element 
print (random_array[::2,:3,:4])

[[[36 47 17 26]
  [32 38 45 47]
  [41 32 32 23]]]


In [23]:
print (random_array[-1,:-2,:4])

[[45 14 23 24]]


In [24]:
random_array1=np.random.randint(low=10,high=50,size=(10,16,8))
print (random_array1.shape)

(10, 16, 8)


In [26]:
random_array1[4:5,-2:]

array([[[49, 49, 45, 45, 33, 37, 22, 36],
        [15, 46, 23, 31, 18, 24, 11, 33]]], dtype=int32)

## Boolen or Mask Indexing 

In [33]:
a=np.array([[1,2],[2,4],[4,5]])
mask=np.array([True,False,True])
print (a)

[[1 2]
 [2 4]
 [4 5]]


In [29]:
a==5

array([[False, False],
       [False, False],
       [False,  True]])

In [30]:
mask =a<4

In [31]:
print (a[mask])

[1 2 2]


In [32]:
mask

array([[ True,  True],
       [ True, False],
       [False, False]])

In [34]:
arr= np.random.randint(low =10,high =50,size=(5,2,3))
arr

array([[[32, 18, 32],
        [40, 10, 18]],

       [[19, 10, 13],
        [38, 46, 16]],

       [[34, 10, 16],
        [21, 47, 43]],

       [[44, 27, 25],
        [35, 28, 40]],

       [[31, 48, 37],
        [11, 18, 18]]], dtype=int32)

In [35]:
arr.shape

(5, 2, 3)

In [36]:
arr.dtype

dtype('int32')

In [37]:
arr.ndim

3

In [40]:
arr.T

array([[[32, 19, 34, 44, 31],
        [40, 38, 21, 35, 11]],

       [[18, 10, 10, 27, 48],
        [10, 46, 47, 28, 18]],

       [[32, 13, 16, 25, 37],
        [18, 16, 43, 40, 18]]], dtype=int32)

In [44]:
arr.reshape((5,2,3))

array([[[32, 18, 32],
        [40, 10, 18]],

       [[19, 10, 13],
        [38, 46, 16]],

       [[34, 10, 16],
        [21, 47, 43]],

       [[44, 27, 25],
        [35, 28, 40]],

       [[31, 48, 37],
        [11, 18, 18]]], dtype=int32)

In [46]:
new_arr=arr.reshape((3,5,2))
new_arr.shape

(3, 5, 2)

In [48]:
flat_arr =new_arr.flatten()
flat_arr.shape

(30,)

In [50]:
arr.sum(axis=0)

array([[160, 113, 123],
       [145, 149, 135]])

In [49]:
print (arr.sum(axis=0)

SyntaxError: incomplete input (4294018038.py, line 1)

In [51]:
arr3.prod(axis=1)

NameError: name 'arr3' is not defined